### ISSUE TITLE
Analysis tutorial with Jupyter Notebook

### ISSUE THREAD

**Issue by kellegra** [brjagger/mmvt_seekr#1]
Hi there, 
`
At this point I was able to set up the input files for MD and BD simulations with the provided package and started the MD simulations for my system of interest. Now I wanted to get through the jupyter notebook tutorial for the analysis section and tried to analyze the aspirin sample output files (I used the mmvt_seekr-master branch from github).

When it comes to cell #3 in the jupyter notebook the script terminates with an AttributeError:
`'Milestone' object has no attribute 'end'
`

This should correspond to analyze.py line 112:
`if milestone.end == "true": # then its an end milestone,..
`

I found the class 'Milestone' in model.py and removed the # in line 415, but the error still remains.
`self.end = end.lower()
`

Do you have any idea what possibly goes wrong? Did I forget to install a needed package?

I am running a conda env with:

- python 3.7
- Jupyter
- Matplotlib
- scipy
- numpy

What I've already done: 
- Added a previously generated and modified milestones.xml file to work with model.py
- name of seekr.py changed to mmvt_seekr.py to get `__init__.py` working properly. Or in `__init__.py` on line 7 'mmvt_seekr' could be changed to 'seekr' instead. 

Best regards, 
Gerald

**Comment by brjagger** [comment]
The generated milestones.xml file was not writing the tag <end>. I have updated the code accordingly, so this tag is now written in the xml file. I have also included a an xml file in the expected results directory in the tutorial that works with the jupyter notebook analysis.
